# Redirect all HTTP traffic to HTTPS and enforce 'www'
[[redirects]]
  from = "http://allofam.com/*"
  to = "https://www.allofam.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.allofam.com/*"
  to = "https://www.allofam.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://allofam.com/*"
  to = "https://www.allofam.com/:splat"
  status = 301
  force = true

# Ensure SPA (Single Page Application) routing works
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Functions Configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Build Settings
[build]
  command = "rm -rf node_modules package-lock.json && npm install && npm run build"
  publish = "dist"
  functions = "netlify/functions"