# Redirect all HTTP traffic to HTTPS (both www and non-www)
[[redirects]]
  from = "http://allofam.com/*"
  to = "https://www.allofam.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.allofam.com/*"
  to = "https://www.allofam.com/:splat"
  status = 301
  force = true

# Ensure your existing redirect to index.html works for your SPA (Single Page App)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[build]
  command = "npm install && npm run build"
  publish = "dist"
